[package]
name = "classroom_app_database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
sqlite = "0.31.0"
clap = { version = "4.0", features = ["derive"] }
actix-web = "4.3.1"
